### ISSUE TITLE
Handle authentication of Task API endpoints

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#100]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Depends on #99 

Implement authenticating a request from Resolve.

A node name is the same as the collection ID.

Auth Process:
1. Check the node header
2. Check the node name is the same as the collection ID
3. Do credential check (password)

Implement this on the `nextjob` and `task/results` endpoints.

### Acceptance Criteria

- [x] Valid credentials are accepted 
- [x] Invalid credentials are rejected

### Tasks

- [x] Implement a custom basic authentication handler (biobanks)
    - https://github.com/biobankinguk/biobankinguk/tree/main/app/Directory/Auth/Basic
- [x] Customise the `authentication` to reflect the auth process above
    - [x] Add the node name check
    - [x] Add the identity password check 
- [x] Apply the authentication on the Controller ( add the attribute [Auth..] ) 
- [x] Configure the app to accept basic authentication (at startup) 
    - [x] https://github.com/biobankinguk/biobankinguk/blob/79d58566bd8d046f17a341cb271de0d13583d12f/app/Directory/Startup/Web/ConfigureWebServices.cs#L150C7-L150C54

### Confirm creation

- [x] This issue is ready
