### ISSUE TITLE
Task Data/Service

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#102]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Create database entities and a service for `Task`

## Datamodel

`Task`
```
id: string
collection: string
created: datetime
completed: datetime? (when a task has been handled by Relay)
```

`SubTask`
```
id: string
owner: fk to SubNode
task: fk to Task
result?: string (present when a result has been received)
```

## Task Service methods

create
get (id)
list 
update

## SubTask Service Methods

create
update

### Acceptance Criteria

- [ ] Data model exists for task 
- [ ] Data model exists for subtask
- [ ] CRUD Service for `Task`
- [ ] CRUD Service for `SubTask`

### Tasks

- [x] New entity classes:
    - [x] Task
    - [x] SubTask
- [x] Register in Db Context
- [x] Migrations
- [ ] Services:
    - [x] TaskService
    - [ ] SubTaskService
- [ ] Register services 
- [ ] Unittests on services:
    - [x] TaskService (all methods)
    - [ ] SubTaskService (all methods)

### Confirm creation

- [x] This issue is ready
