### ISSUE TITLE
SubNode data model

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#105]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A data model to store what is effectively a "Collection".

`SubNode`
```
id: string 
<ICollection> RelayUser
```

Subclass `IdentityUser` as `RelayUser` add
```
<ICollection> ... SubNode
```
 

### Acceptance Criteria

- [x] A `SubNode` table exists 
- [ ] It links M2M to `IdentityModel`

### Tasks

- [x] Create entities as above
- [x] Add to db context
- [x] Migrations

### Confirm creation

- [x] This issue is ready
