### ISSUE TITLE
Relay dummy Task API endpoints

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/hutch-cohort-discovery#111]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

In order to expedite integration testing Resolve, and an "end-to-end" experience with the local development stack, we should partially implement the relevant Task API endpoints (nextjob and result) so that they are interactable with on the correct interface.

This does not include Authentication at this time.

It does not perform any logic and so does not depend on the queue, the database or upstream Task API functionality.

### NextJob

- [x] accepts any collection id
- [x] randomly returns a job or nothing:
    - 50% chance returns an appropriate payload based query type if specified, or availability if not.
    - 50% chance returns 204

### Result
- [x] accepts any uuid, collection id
- [x] returns 200 OK "Job saved" per Task API success expectation

### Tasks

- [x] Modify NextJob endpoint
    - [x] Add sample payloads
    - [x] Add ranomisation logic
    - [x] Evaluate collection id to check for type
    - [x] return appropriate payload (or 204)
- [x] Modify Result endpoint
    - [x] Return expected success

### Confirm creation

- [x] This issue is ready
