### ISSUE TITLE
Deployment Documentation

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#115]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Documentation for deploying Resolve.

Preferable on a VM, and Azure.

### Acceptance Criteria

- [ ] A guide for deploying Resolve on a VM exists
- [ ] A guide for deploying Resolve on Azure exists

### Tasks

- [ ] Task A.
- [ ] Task B.
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
