### ISSUE TITLE
Development Documentation

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#116]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Development documentation for Resolve.

Quickstart dev setup - environment
Architecture
Design
Contributing

### Acceptance Criteria

- [ ] Development documentation for Resolve exists

### Tasks

- [ ] Task A.
- [ ] Task B.
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
