### ISSUE TITLE
Resolve Docker Compose Deployment

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#117]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A sample for deploying Resolve with Docker Compose, in the main `hutch` repository.
This should pull from our Github registry.

`samples/Bunny/docker-compose.resolve.yml`

### Acceptance Criteria

- [ ] `docker compose up` can run the Resolve app

### Tasks

- [x] A new docker compose
- [ ] Configuration 
    - [ ] Default to single type queue (don't configure type queues)
    - [ ] Database config
    - [ ] Task_API config
- [x] Run the resolve app from the Github registry (don't pin to any version!)

### Confirm creation

- [x] This issue is ready
