### ISSUE TITLE
Azure deployment

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#118]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A way to deploy Resolve quickly to Azure cloud infrastructure.

### Acceptance Criteria

- [ ] Resolve can be configured, deployed to Azure with a guided Portal experience
- [ ] Specification of resources are configurable
-

### Tasks

- [ ] Task A.
- [ ] Task B.
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
