### ISSUE TITLE
Resolve Typed Endpoint

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#121]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We would like to be able to "poll" the Task API, for a specific "Job" "type", for example - Availability, Distribution.

This means we are adding `.a` for a Availability query, `b`/`c`. 

### Acceptance Criteria

- [ ] Resolve can query for specific job types

### Tasks

- [ ] Add a new `settings.py` variable - `TASK_API_TYPE` which can be `a|b|c`
- [ ] In the polling request url, if this variable exists - append it to the URL with the `.` like this: `/{collection_id}.a`

### Confirm creation

- [x] This issue is ready
