### ISSUE TITLE
Quickstart Development

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#122]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A quickstart for getting Resolve running in development.

Think about what you would want as a dev to get started on this project.

There is a dev `docker-compose.yml` in the root. 

Environment (poetry)
Reference configuration

### Acceptance Criteria

- [ ] Documentation for dev setup to run Resolve

### Tasks

- [ ] Requirements
- [ ] Environment setup (Python version, Poetry)
- [ ] Steps
    - [ ] `docker compose up db` (for the db)
    - [ ] Load in OMOP CDM
    - [ ] `poetry start`

### Confirm creation

- [x] This issue is ready
