### ISSUE TITLE
Build images on PR

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#125]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We are publishing a few images on merge to main.

But we are not building them on PR to check they still build.

### Acceptance Criteria

- [ ] Build checks on images on PR
    - [ ] Relay
    - [ ] Resolve Daemon

### Tasks

- [ ] Add Relay build
- [ ] Add Resolve build

### Confirm creation

- [x] This issue is ready
