### ISSUE TITLE
Relay Docker Compose Sample

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#128]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A docker compose sample for running the Relay stack, that utilises our Github registry.

In Hutch repo, `samples/Bunny/compose.relay.yml`

### Acceptance Criteria

- [ ] Relay can be ran using Docker Compose

### Tasks

- [ ] Task A.
- [ ] Task B.
- [ ] Unit tests.
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
