### ISSUE TITLE
Relay Migrations Pattern

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#134]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We need to handle database migrations for the images we are publishing.

.NET can run migrations on startup, so need to implement this, but we want to do it as opt in.

Opt'ing in based on environment variable

Additionally we want to provide a CLI for running migrations.

Our sample docker compose can opt in, and comment it for clarity.

### Acceptance Criteria

- [ ] Migrations can be run on startup with an opt in environment variable
- [ ] Migrations can be run through a CLI

### Tasks

- [ ] Turn on migrations on startup 
- [ ] Add a environment variable `MIGRATIONS_ON_STARTUP`?
- [ ] Add access to the `dotnet ef` CLI

### Confirm creation

- [x] This issue is ready
