### ISSUE TITLE
Relay Obfuscation

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#135]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Relay should be able to be configured to perform Low Number Suppression (LNS) and Rounding of the AGGREGATED results (i.e. after all results (which may themselves have been obfuscated) have come back from Resolve nodes, further obfuscation is applied before results are returned to upstream task API).

### Acceptance Criteria

- [ ] LNS is implemented
- [ ] Rounding is implemented
- [ ] These values are configurable
- [ ] Results can be obfuscated before returned to the upstream Task API 

### Tasks

- [ ] new `ObfuscationService`
- [ ] Options configuration
- [ ] Method for LNS
- [ ] Method for rounding
- [ ] Register service
- [ ] Add to results being returned

### Confirm creation

- [x] This issue is ready
