### ISSUE TITLE
Aggregate SubTask results for each Task

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-cohort-discovery#137]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Aggregate SubTask Results.Count per subtask in a Task

### Acceptance Criteria

- [ ] Aggregates count in all SubTask.Results for a Task
- [ ] Submits count to TaskApi

### Tasks

- [ ] If all subtasks for a parent task complete aggregate all counts
- [ ]Create Results object 
- [ ] Send to TaskApi

### Confirm creation

- [x] This issue is ready
