### ISSUE TITLE
Rename Resolve to Bunny

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#142]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Everything named "Resolve" should be called "Bunny".

### Acceptance Criteria

- [ ] Everything is now bunny

### Tasks

- [ ] ctrl+f "resolve"
- [ ] replace bunny
- [ ] fix any issues

### Confirm creation

- [x] This issue is ready
