### ISSUE TITLE
Make Crate Submission Optional

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-cohort-discovery#156]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Create FeatureFlag for using RO-Crates for submitting to TRE-FX Sub Layer

### Acceptance Criteria

- [ ] RO-Crate creation and submission is optional.
- [ ] `UseRoCrate` feature flag exists with default false

### Tasks

- [ ] Create `UseRoCrate` Feature Flag
- [ ] Add check on crate creation and submission

### Confirm creation

- [x] This issue is ready
