### ISSUE TITLE
Submit actual TES message to Submission Layer task API

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-cohort-discovery#157]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Create a correct TES message that be run by a TES implementation.

### Acceptance Criteria

- [ ] Create TES message for executing the `beacon-omop-worker` image
- [ ] POST TES message to Submission API

### Tasks

- [ ] Create TES message with: 
  - [ ] container image (set image version in config options?)
  - [ ] runs individuals commands 
  - [ ] env variables for connecting to DB
  - [ ] output directory (minio bucket) 
- Submit with TES message if `UseRoCrate` flag is false

### Confirm creation

- [x] This issue is ready
