### ISSUE TITLE
Repository Housekeeping

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#67]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We want to set up sensible names for repos.

### Acceptance Criteria

- [x] Sensible names for repos now exist
- [x] A coherent idea of the Hutch technical brand 

### Tasks

- [x] Come up with a name for `hutch-r/discovery/r/quest` repo
- [x] `rquest-tools` -> `hutch-cohort-discovery` 
- [x] `beacon-tools` -> `hutch-beacon`
- [x] `hutch` -> `hutch-trefx`
- [x] `beacon-omop-worker-workflows` -> `hutch-beacon-workflows`
- [x] Move (or fork?) `hdr/rquest-omop-worker-workflows` to `health-informatics/hutch-cohort-discovery-workflows`
- [x] New `hutch` repo that signposts to the relevant Hutch repo based on the user reqs.

### Confirm creation

- [x] This issue is ready
