### ISSUE TITLE
Resolve Setup

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#70]
The existing `rquest-omop-worker` has a core library, and then an CLI entrypoint (scripts). 
We should add another entrypoint for Resolve, that is just a polling daemon for Relay.

# Acceptance Criteria

- [ ] A published image to Github registry

# Tasks

- [x] Add polling entrypoint "stub" (`print hello world`) in `resolve-daemon`
- [x] Add entrypoint to `pyproject.toml`
- [x] Add Dockerfile `Dockerfile.daemon`
- [ ] Add workflow to build/tag/publish 
    - [ ] Commit hash, timestamp, "dev-latest" 
- [x] Add to Resolve service to root `docker-compose.yml`
    - [ ] Add Postgres volume mount
