### ISSUE TITLE
Resolve Pre-Setup

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#71]
Preparing existing project for the project setup of Resolve.

## Acceptance Criteria

- [x] The legacy rquest-omop-worker functionality is preserved and works
    - [x] Can run the CLI tool directly, given a query and target DB - will return a result
    - [x] Can do `Docker run` on the image, given the same and will return a result
- [x] A new Resolve project exists
- [x] The "project" has been converted to Poetry
- [x] Build/push image workflows to Dockerhub still work

## Tasks

- [x] Rename `rquest-omop-worker/rquest-omop-worker` to `resolve/core`
- [x] Move code from `scripts/worker.py` to `cli/__init__.py`
    - [x] Rename entrypoint in `pyproject.toml`:  `resolve-cli`
    - [x] And fix `scripts.worker:main` route, to `cli:main`
    - [x] And fix in `Dockerfile`: `resolve-cli` as entrypoint
- [x] Rename build path in `workflows/release.rquest....`
- [x] Rework the `pyproject.toml` to use Poetry instead, for example: https://github.com/Health-Informatics-UoN/beacon-tools/blob/main/app/beacon-omop-worker/pyproject.toml
    - [ ] `poetry init` 
- [x] Update the Dockerfile to use Poetry instead, for example: https://github.com/Health-Informatics-UoN/Carrot-Mapper/blob/master/app/Dockerfile
- [x] Rename Dockerfile to `Dockerfile.cli`, and update the build/release workflow accordingly
