### ISSUE TITLE
Resolve Azure Deployment - Investigation

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-cohort-discovery#77]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We should have a docker image in our public registry.

As a data partner, I want to deploy Resolve as easy as possible, preferably in one click.

We need infrastructure as code (Bicep) to describe this process.

Investigate best way to deploy docker image on azure.
**Time spent no more than half a day.**

### Acceptance Criteria

- [ ] Decide on how/where to deploy the Resolve image

### Tasks

- [ ] Investigate best way to deploy docker image on azure.
- [ ] Options: [Container Instances](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-quickstart-portal), [Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/quickstart-portal), Appservice, [WebJobs](https://learn.microsoft.com/en-us/azure/app-service/webjobs-create?tabs=windowscode)

### Confirm creation

- [x] This issue is ready

**Comment by AndyRae** [comment]
Not Azure Web Jobs (not for docker)
Not Azure Container Instances (not for long running)
Not Azure app service (don't need http)

Azure Container Apps:

https://learn.microsoft.com/en-us/azure/container-apps/overview
_There are two types of compute resources in Azure Container Apps: apps and jobs.

Apps are services that run continuously. If a container in an app fails, it restarts automatically. Examples of apps include HTTP APIs, web apps, and background services that continuously process input._
