### ISSUE TITLE
Resolve Obfuscation

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-cohort-discovery#78]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Configure Obfuscation as environment variables
One setting for each: Low Number Suppression & Rounding

Results Modifiers Structure:
```jsonc
[
  {
    "id": "Low Number Suppression", // or "Rounding"
    "threshold": 0, // for LNS only
    "nearest": 0 // for Rounding only
  },
  {
    "id": "Low Number Suppression", // or "Rounding"
    "threshold": 0, // for LNS only
    "nearest": 0 // for Rounding only
  }
]
```

### Acceptance Criteria

- [x] Applies Low Number Suppression when configured and relevant
- [x] Applies Rounding when configured and relevant
- [x] Test obfuscation methods

### Tasks

- [x] Add environment variables and read into the app.
    - [x] LOW_NUMBER_SUPPRESSION_THRESHOLD
    - [x] ROUNDING_TARGET
- [x] Refactor `execute_query` to not depend directly on `args`
    - [x] Change `execute_query` signature to accept `query` and `result_modifiers`
    - [x] Change CLI to parse `args` and pass the correct values on to `execute_query`
        - [x] Change CLI to call `get_results_modifiers_from_str` on its modifiers arg before passing to `execute_query`
    - [x] `execute_query` needs to determine query type by itself:
        - test the "analysis" property of the `query`:
            - if not present, it's an availability query
            - if DISTRIBUTION it's distribution
            - any other value currently can be ignored as it's not supported by the query resolvers.
   - [x] Daemon reads env variables and builds results_modifiers list to pass to `execute_query`:
       - [x] which is the right order?
       - [x] if LOW_NUMBER_SUPPRESSION_THRESHOLD is set, add it to the list as a LNS entry with a `threshold`
       - [x] if ROUNDING_TARGET is set, add it to the list as a Rounding entry with a `nearest` value
- [ ] When configured then run `apply_filters2` method to the results using the configuration (this should already be handled by `execute_query`

### Confirm creation

- [x] This issue is ready
