### ISSUE TITLE
Relay Dev Environment

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#87]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We need to make it easier to get the dev stack running.

There is an existing docker compose with a postgres db.

Would be useful;
 - RabbitMQ
 - Relay Container 
 - Resolve Container (in progress)

### Acceptance Criteria

- [x] `docker compose up` runs the app stack

### Tasks

- [x] Add RabbitMQ
- [x] Add Relay container

### Confirm creation

- [x] This issue is ready
