### ISSUE TITLE
Relay API Endpoints

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#89]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We need an API for Resolve to connect to.
For now, this can be stub methods that throw `NonImplemented` so we can build around it.

A GET `/task/nextjob/{collectionId}` will return the Next Job for a Node from its queue.
A POST to `/task/result/{uuid}/{collectionId}` will return the result to Rquest.

We want Swagger docs also.

### Acceptance Criteria

- [x] GET request
- [x] POST request
- [x] Swagger docs of the API

### Tasks

- [x] Setup .NET API in program.cs
- [x] Setup Controller
- [x] Setup GET request (throw not implemented)
- [x] Setup POST request (throw not implemented)

### Confirm creation

- [x] This issue is ready
