### ISSUE TITLE
Relay Task GET Endpoint

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#92]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Depends on #91 for ease.

A GET API request from Resolve should now return a job from its queue.

Think over the Types of jobs in Rabbit, and return Types from the endpoint (one endpoint returning multiple types of jobs etc.)

### Acceptance Criteria

- [x] A job is returned from a GET Request to Relay

### Tasks

- [x] Add `next` method given ID to queue service
- [x] Call service from controller and return 

### Confirm creation

- [x] This issue is ready
