### ISSUE TITLE
Relay Node Registration

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#94]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A CLI for an internal Relay user to register a new Node with Relay.

This process will add the Node to the database.

### Acceptance Criteria

- [ ] A node can be added to Relay through the CLI

### Tasks

- [ ] Add CLI entrypoint
- [ ] Add Node registration

### Confirm creation

- [x] This issue is ready
