### ISSUE TITLE
Hutch Tools Doc Site

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#96]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Using Nextra - deploy a documentation site for Hutch.

So this is in the Hutch main repo:

https://github.com/Health-Informatics-UoN/hutch

https://nextra.site/

Example workflow: https://github.com/Health-Informatics-UoN/rcc-monitor/blob/main/.github/workflows/deploy.docs.yml

### Acceptance Criteria

- [ ] A Github pages docs site is deployed
- [ ] Hutch branding is in place
- [ ] It links out to the Hutch TREFX docs
- [ ] Some topline docs for Hutch Bunny exist

### Tasks

- [ ] New Nextra site - `website` directory in Hutch repo
- [ ] Implement branding
- [ ] Implement link out to Hutch trefx
- [ ] Implement Github publish workflow

### Confirm creation

- [x] This issue is ready
