### ISSUE TITLE
Resolve Authentication

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#97]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We are doing basic auth.

https://requests.readthedocs.io/en/latest/user/authentication/

### Acceptance Criteria

- [x] Resolve can send a successful authenticated request
    - [ ] Job fetching are authenticated
    - [x] Results sending are authenticated

### Tasks

- [x] `settings.py` Add environment variables for Task API:
    - [x] `username`
    - [x] `password` 
- [x] Add authorization header where Requests are made (implement basic auth)
    - [x] If Requests are made in multiple places - combine this into using a function 

### Confirm creation

- [x] This issue is ready
