### ISSUE TITLE
Implement .NET Identity

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#98]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We'd like to use .NET identity for our auth implementation at least.

### Acceptance Criteria

- [ ] .NET identity is implemented

### Tasks

- [x] Configure Identity (just store users, no roles etc., nothing else)
- [x] Entity Framework add dependencies (postgres)
- [x] Add Db Context ( inherit from Identity)
- [x] Migrations
- [x] Change docker compose to make Relay depend on Postgres

### Confirm creation

- [x] This issue is ready
