### ISSUE TITLE
CLI adding users

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-cohort-discovery#99]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We need a CLI for adding users.

This can be taken from Biobanks

https://github.com/biobankinguk/biobankinguk

Adding a `SubNode` is adding a user, subnode, and linking them.

### Acceptance Criteria

- [x] We can add users (Resolve nodes) through a CLI
- [x] This is done through only specifying a username (node name)
- [x] The password is logged out back to the CLI user

### Tasks

- [x] Implement Startup pattern (biobanks!)
- [x] Implement CLI (biobanks! with changes to have the password generated)
- [x] Implement adding a `SubNode`
    - [x] This creates a user and links it to the `SubNode`
- [x] Handle the `UniqueConstraint` exception on SubNode `id`

### Confirm creation

- [x] This issue is ready
